spring:
  flyway:
    enabled: true

  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true

    show-sql: true  # sql 출력
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ENC(qP6HBQhSvjIz2TaTreM7sSaXKpJt3IZaiNtjVK6+D6Y2vRiYJC5pxbTj5BoKswvAfeRr447cN8NWZA1Zl/QNLx6TZfa6X16G+6Xr/ibbIYPUieioNkHJbdz5PsTHuN1N)
      username: ENC(KM07v58ckwqQ3LPUno5zqi2LUWCr4bcl)
      password: ENC(UXjl58kP+8yCA1XciTnqUy/xYqaqVHVXVapkgKDOAwk=)
      slave:
        slave-1:
          name: slave-1
          url: ENC(1CqLZsz0LJNOaAzfBiBOlW8DGK5xkUNActscZydTIpdjY9s/x5Bda/O09Td8YYpVaGnoSjsZfa7AQvvox1x6ShmUeKwqO9mDbci14wsJrho2Q49dTCWAf9dWtMge6Mro)
          username: ENC(KM07v58ckwqQ3LPUno5zqi2LUWCr4bcl)
          password: ENC(UXjl58kP+8yCA1XciTnqUy/xYqaqVHVXVapkgKDOAwk=)
          driver-class-name: org.mariadb.jdbc.Driver


jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
