server:
  port: 8080
  servlet:
    context-path: /

spring:

  flyway:
    enabled: true

  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:43306/shopdb?serverTimezone=UTC&characterEncoding=UTF-8
      username: replication
      password: replication-pass
      slave:
        slave-1:
          name: slave-1
          url: jdbc:mariadb://localhost:53306/shopdb?serverTimezone=UTC&characterEncoding=UTF-8
          username: root
          password: root-pass
          driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한

  messages:
    basename: messages, errors

  profiles:
    active: local
    include:
      - aws


logging:
  level:
    org.hibernate.type: trace # sql binding 값 출력
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE
elasticsearch:
  host: 127.0.0.1
  port: 9200

