spring:
  flyway:
    enabled: false

  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true

    show-sql: true  # sql 출력
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ENC(77+AOmpXEF/ex64O39PoC68yo65iabkeBrCtTkveNSha5D9VZAxrVPDDWteGar2pMKFTKuYZC4hmn+bMj4nj/g7wGf6U+Xkn8Xqb09OR0OMIqD8Z2OQf5w==)
      username: ENC(guBiz4Lq+Oki9Xd/DH/3iCtbwaNG0JqZ)
      password: ENC(Vi1jn3LAtx6zij53o2Pi4EEw5VtqQluSKECqwvfopqE=)
      slave:
        slave-1:
          name: slave-1
          url: ENC(hfmynX75g8Y5Gp6f0CaGvuNP7X7UnxXCLWiI1oEsCN/X6zS1nOCT8IjW2wbkKE/RV6hlNvyXI5XorcY4axZWADqZ4hmdpBubuspoAa4jLTP5duRQw3rwQA==)
          username: ENC(OEItQBJ5CgZiCt0Qux/F3g==)
          password: ENC(MCnhkCr0C5GpIDyf0FRwyf4PqWSLoBEr)
          driver-class-name: com.mysql.cj.jdbc.Driver



jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

elasticsearch:
  host: ENC(/zN564TDGf7tqc0pHS86fekwH+I+5N9K)
  port: 9200