spring:
  flyway:
    enabled: true

  profiles:
    include: aws

  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true

    show-sql: true  # sql 출력
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ENC(UPHfQwLj+0In5sKZ1OSY2DagSVGIJI+hNx15Axc+dNAS5HvKzmhxq57W+7xeAa2zeDxbWiMdxCfVsWloX/b0gtwIQ9dkaiNAJ5O3SIslQ0W2O9IE/Kd3Z6nNtGQSYw1J)
      username: ENC(Njk7nM6K6Lxqro31Vc4dDIgpkOe13Rmz)
      password: ENC(AAISN8l3s6xRwNcHpViG5ow9rfPH65iG+PHLMRG5U7k=)
      slave:
        slave-1:
          name: slave-1
          url: ENC(XTeuvuANKhO2nIqFnFxwr5c7QOywWFbeIZLt2/Qmo3ZTZh4w0afbtFpVz/tb7T/An5G0bNPLp2ijykQ14Z27oE8FrYI3YYnwoubXlF5uREC/9j8KTqoY079yGIXnppCX)
          username: ENC(Njk7nM6K6Lxqro31Vc4dDIgpkOe13Rmz)
          password: ENC(AAISN8l3s6xRwNcHpViG5ow9rfPH65iG+PHLMRG5U7k=)
          driver-class-name: org.mariadb.jdbc.Driver

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

elasticsearch:
  host: localhost
  port: 9200
