version: "3.7"

services:
  db_master:
    image: mariadb
    container_name: ${CONTAINER_MASTER_NAME}
    ports:
      - "${MYSQL_MASTER_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./master:/var/lib/mysql
    env_file:
      - .env

  db_slave:
    image: mariadb
    container_name: ${CONTAINER_SLAVE_NAME}
    ports:
      - "${MYSQL_SLAVE_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./slave:/var/lib/mysql
    env_file:
      - .env
    depends_on:
      - db_master