name: shoppingmall

on:
  push:
    branches: [ develop ]

env:
  NAME: hyun6ik
  REPO: shoppingmall

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.15.2

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          submodules: true

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build
        run: |
          docker build \
            -f Dockerfile \
            -t ${{env.NAME}}/${{env.REPO}}:latest .
      - name: Docker image Push
        run: |
          docker push ${{env.NAME}}/${{env.REPO}}:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:
      - name: deploy run
        run: |
          sudo sh /home/ubuntu/run.sh

  deploy-replica:
    needs: build
    name: Deploy-Replica
    runs-on: [ self-hosted, replica ]
    steps:
      - name: deploy run
        run: |
          sudo sh /home/ubuntu/run.sh
