name: deploy

on:
  push:
    branches: [ develop ]
jobs:
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:
      - name: deploy run
        run: |
          sudo sh /home/ubuntu/run.sh
