name: deploy-replica

on:
  push:
    branches: [ develop ]
jobs:
  deploy:
    needs: build
    name: Deploy-Replica
    runs-on: [ self-hosted, replica ]
    steps:
      - name: deploy run
        run: |
          sudo sh /home/ubuntu/run.sh
